openapi: 3.2.0
info:
  version: '9.0'
  title: NGINX Plus REST HTTP Keyvals API
  description: NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
servers:
- url: /api/9
tags:
- name: HTTP Keyvals
paths:
  /http/keyvals/:
    get:
      tags:
      - HTTP Keyvals
      summary: NGINX Return Key-Value Pairs from All HTTP Keyval Zones
      description: Returns key-value pairs for each HTTP keyval shared memory [zone](https://nginx.org/en/docs/http/ngx_http_keyval_module.html#keyval_zone).
      operationId: getHttpKeyvalZones
      parameters:
      - name: fields
        in: query
        description: If the “<literal>fields</literal>” value is empty, then only HTTP keyval zone names will be output.
        x-example: ''
        schema:
          type: string
      responses:
        '200':
          description: Success
          x-microcks-refs:
          - name: getHttpKeyvalZones200Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxHTTPKeyvalZonesMap'
              example:
                keyval_zone:
                  key1: value1
                  key2: value2
                  key3: value3
                one:
                  arg1: value1
                  arg2: value2
                  arg3: value3
        '404':
          description: Unknown version (*UnknownVersion*)
          x-microcks-refs:
          - name: getHttpKeyvalZones404Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /http/keyvals/{httpKeyvalZoneName}:
    parameters:
    - name: httpKeyvalZoneName
      in: path
      description: The name of an HTTP keyval shared memory zone.
      required: true
      x-example: example_httpKeyvalZoneName
      schema:
        type: string
    get:
      tags:
      - HTTP Keyvals
      summary: NGINX Return Key-Value Pairs from an HTTP Keyval Zone
      description: Returns key-value pairs stored in a particular HTTP keyval shared memory [zone](https://nginx.org/en/docs/http/ngx_http_keyval_module.html#keyval_zone).
      operationId: getHttpKeyvalZoneKeysValues
      parameters:
      - name: key
        in: query
        description: Get a particular key-value pair from the HTTP keyval zone.
        x-example: ''
        schema:
          type: string
      responses:
        '200':
          description: Success
          x-microcks-refs:
          - name: getHttpKeyvalZoneKeysValues200Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxHTTPKeyvalZone'
              example:
                key1: value1
                key2: value2
                key3: value3
        '404':
          description: 'Keyval not found (*KeyvalNotFound*),

            keyval key not found (*KeyvalKeyNotFound*),

            unknown version (*UnknownVersion*)

            '
          x-microcks-refs:
          - name: getHttpKeyvalZoneKeysValues404Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    post:
      tags:
      - HTTP Keyvals
      summary: NGINX Add a Key-Value Pair to the HTTP Keyval Zone
      description: Adds a new key-value pair to the HTTP keyval shared memory [zone](https://nginx.org/en/docs/http/ngx_http_keyval_module.html#keyval_zone). Several key-value pairs can be entered if the HTTP keyval shared memory zone is empty.
      operationId: postHttpKeyvalZoneData
      responses:
        '201':
          description: Created
        '400':
          description: 'Invalid JSON (*KeyvalFormatError*),

            invalid key format (*KeyvalFormatError*),

            key required (*KeyvalFormatError*),

            keyval timeout is not enabled (*KeyvalFormatError*),

            only one key can be added (*KeyvalFormatError*),

            reading request body failed *BodyReadError*)

            '
          x-microcks-refs:
          - name: postHttpKeyvalZoneData400Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
        '404':
          description: 'Keyval not found (*KeyvalNotFound*),

            unknown version (*UnknownVersion*)

            '
          x-microcks-refs:
          - name: postHttpKeyvalZoneData404Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
        '405':
          description: Method disabled (*MethodDisabled*)
          x-microcks-refs:
          - name: postHttpKeyvalZoneData405Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
        '409':
          description: 'Entry exists (*EntryExists*),

            key already exists (*KeyvalKeyExists*)

            '
          x-microcks-refs:
          - name: postHttpKeyvalZoneData409Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
        '413':
          description: Request Entity Too Large
          x-microcks-refs:
          - name: postHttpKeyvalZoneData413Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
        '415':
          description: JSON error (*JsonError*)
          x-microcks-refs:
          - name: postHttpKeyvalZoneData415Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NginxHTTPKeyvalZonePostPatch'
        description: A key-value pair is specified in the JSON format. Several key-value pairs can be entered if the HTTP keyval shared memory zone is empty. Expiration time in milliseconds can be specified for a key-value pair with the *expire* parameter which overrides the [*timeout*](https://nginx.org/en/docs/http/ngx_http_keyval_module.html#keyval_timeout) parameter of the <a href="https://nginx.org/en/docs/http/ngx_http_keyval_module.html#keyval_zone">keyval_zone</a> directive.
        required: true
    patch:
      tags:
      - HTTP Keyvals
      summary: NGINX Modify a Key-Value or Delete a Key
      description: Changes the value of the selected key in the key-value pair, deletes a key by setting the key value to <literal>null</literal>, changes expiration time of a key-value pair. If <a href="https://nginx.org/en/docs/stream/ngx_stream_zone_sync_module.html#zone_sync">synchronization</a> of keyval zones in a cluster is enabled, deletes a key only on a target cluster node. Expiration time in milliseconds can be specified for a key-value pair with the *expire* parameter which overrides the [*timeout*](https://nginx.org/en/docs/http/ngx_http_keyval_module.html#keyval_timeout) parameter of the <a href="https://nginx.org/en/docs/http/ngx_http_keyval_module.html#keyval_zone">keyval_zone</a> directive.
      operationId: patchHttpKeyvalZoneKeyValue
      responses:
        '204':
          description: Success
        '400':
          description: 'Invalid JSON (*KeyvalFormatError*),

            key required (*KeyvalFormatError*),

            keyval timeout is not enabled (*KeyvalFormatError*),

            only one key can be updated (*KeyvalFormatError*),

            reading request body failed *BodyReadError*)

            '
          x-microcks-refs:
          - name: patchHttpKeyvalZoneKeyValue400Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
        '404':
          description: 'Keyval not found (*KeyvalNotFound*),

            keyval key not found (*KeyvalKeyNotFound*),

            unknown version (*UnknownVersion*)

            '
          x-microcks-refs:
          - name: patchHttpKeyvalZoneKeyValue404Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
        '405':
          description: Method disabled (*MethodDisabled*)
          x-microcks-refs:
          - name: patchHttpKeyvalZoneKeyValue405Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
        '413':
          description: Request Entity Too Large
          x-microcks-refs:
          - name: patchHttpKeyvalZoneKeyValue413Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
        '415':
          description: JSON error (*JsonError*)
          x-microcks-refs:
          - name: patchHttpKeyvalZoneKeyValue415Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NginxHTTPKeyvalZonePostPatch'
        description: A new value for the key is specified in the JSON format.
        required: true
    delete:
      tags:
      - HTTP Keyvals
      summary: NGINX Empty the HTTP Keyval Zone
      description: Deletes all key-value pairs from the HTTP keyval shared memory [zone](https://nginx.org/en/docs/http/ngx_http_keyval_module.html#keyval_zone). If <a href="https://nginx.org/en/docs/stream/ngx_stream_zone_sync_module.html#zone_sync">synchronization</a> of keyval zones in a cluster is enabled, empties the keyval zone only on a target cluster node.
      operationId: deleteHttpKeyvalZoneData
      responses:
        '204':
          description: Success
        '404':
          description: 'Keyval not found (*KeyvalNotFound*),

            unknown version (*UnknownVersion*)

            '
          x-microcks-refs:
          - name: deleteHttpKeyvalZoneData404Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
        '405':
          description: Method disabled (*MethodDisabled*)
          x-microcks-refs:
          - name: deleteHttpKeyvalZoneData405Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    NginxHTTPKeyvalZonePostPatch:
      title: HTTP Keyval Shared Memory Zone
      description: 'Contents of an HTTP keyval shared memory zone

        when using the POST or PATCH methods.

        '
      type: object
      example:
        key1: value1
        key2: value2
        key3:
          value: value3
          expire: 30000
    NginxHTTPKeyvalZone:
      title: HTTP Keyval Shared Memory Zone
      description: 'Contents of an HTTP keyval shared memory zone

        when using the GET method.

        '
      type: object
      example:
        key1: value1
        key2: value2
        key3: value3
    NginxError:
      title: Error
      description: 'nginx error object.

        '
      type: object
      properties:
        error:
          type: object
          properties:
            status:
              type: integer
              description: HTTP error code.
              example: 200
            text:
              type: string
              description: Error description.
              example: example-text
            code:
              type: string
              description: Internal nginx error code.
              example: 200
          example: {}
        request_id:
          type: string
          description: The ID of the request, equals the value of the <a href="https://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_id">$request_id</a> variable.
          example: example-request_id
        href:
          type: string
          description: Link to reference documentation.
          example: example-href
    NginxHTTPKeyvalZonesMap:
      title: HTTP Keyval Shared Memory Zones
      description: 'Contents of all HTTP keyval shared memory zones.

        '
      type: object
      additionalProperties:
        $ref: '#/components/schemas/NginxHTTPKeyvalZone'
      example:
        keyval_zone:
          key1: value1
          key2: value2
          key3: value3
        one:
          arg1: value1
          arg2: value2
          arg3: value3
