openapi: 3.2.0
info:
  version: '9.0'
  title: NGINX Plus REST Stream Limit Conns API
  description: NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
servers:
- url: /api/9
tags:
- name: Stream Limit Conns
paths:
  /stream/limit_conns/:
    get:
      tags:
      - Stream Limit Conns
      summary: NGINX Return Status of All Stream Limit_conn Zones
      description: Returns status information for each stream [limit_conn zone](https://nginx.org/en/docs/stream/ngx_stream_limit_conn_module.html#limit_conn_zone).
      operationId: getStreamLimitConnZones
      parameters:
      - in: query
        name: fields
        description: Limits which fields of limit_conn zones will be output. If the “<literal>fields</literal>” value is empty, then only zone names will be output.
        x-example: ''
        schema:
          type: string
      responses:
        '200':
          description: Success
          x-microcks-refs:
          - name: getStreamLimitConnZones200Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxStreamLimitConnZonesMap'
              example: example
        '404':
          description: Unknown version (*UnknownVersion*)
          x-microcks-refs:
          - name: getStreamLimitConnZones404Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /stream/limit_conns/{streamLimitConnZoneName}:
    parameters:
    - name: streamLimitConnZoneName
      in: path
      description: The name of a [limit_conn zone](https://nginx.org/en/docs/stream/ngx_stream_limit_conn_module.html#limit_conn_zone).
      required: true
      x-example: example_streamLimitConnZoneName
      schema:
        type: string
    get:
      tags:
      - Stream Limit Conns
      summary: NGINX Return Status of an Stream Limit_conn Zone
      description: Returns status of a particular stream [limit_conn zone](https://nginx.org/en/docs/stream/ngx_stream_limit_conn_module.html#limit_conn_zone).
      operationId: getStreamLimitConnZone
      parameters:
      - name: fields
        in: query
        description: Limits which fields of the [limit_conn zone](https://nginx.org/en/docs/stream/ngx_stream_limit_conn_module.html#limit_conn_zone) will be output.
        x-example: ''
        schema:
          type: string
      responses:
        '200':
          description: Success
          x-microcks-refs:
          - name: getStreamLimitConnZone200Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxStreamLimitConnZone'
              example:
                passed: 15
                rejected: 0
                rejected_dry_run: 2
        '404':
          description: 'limit_conn not found (*LimitConnNotFound*),

            unknown version (*UnknownVersion*)

            '
          x-microcks-refs:
          - name: getStreamLimitConnZone404Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    delete:
      tags:
      - Stream Limit Conns
      summary: NGINX Reset Statistics for a Stream Limit_conn Zone
      description: Resets the connection limiting statistics.
      operationId: deleteStreamLimitConnZoneStat
      responses:
        '204':
          description: Success
        '404':
          description: 'limit_conn not found (*LimitConnNotFound*),

            unknown version (*UnknownVersion*)

            '
          x-microcks-refs:
          - name: deleteStreamLimitConnZoneStat404Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
        '405':
          description: Method disabled (*MethodDisabled*)
          x-microcks-refs:
          - name: deleteStreamLimitConnZoneStat405Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    NginxError:
      title: Error
      description: 'nginx error object.

        '
      type: object
      properties:
        error:
          type: object
          properties:
            status:
              type: integer
              description: HTTP error code.
              example: 200
            text:
              type: string
              description: Error description.
              example: example-text
            code:
              type: string
              description: Internal nginx error code.
              example: 200
          example: {}
        request_id:
          type: string
          description: The ID of the request, equals the value of the <a href="https://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_id">$request_id</a> variable.
          example: example-request_id
        href:
          type: string
          description: Link to reference documentation.
          example: example-href
    NginxStreamLimitConnZone:
      title: Stream Connections Limiting
      type: object
      properties:
        passed:
          type: integer
          description: The total number of connections that were neither limited nor accounted as limited.
          example: 0
        rejected:
          type: integer
          description: The total number of connections that were rejected.
          example: 0
        rejected_dry_run:
          type: integer
          description: The total number of connections accounted as rejected in the <a href="https://nginx.org/en/docs/stream/ngx_stream_limit_conn_module.html#limit_conn_dry_run">dry run</a> mode.
          example: 0
      example:
        passed: 15
        rejected: 0
        rejected_dry_run: 2
    NginxStreamLimitConnZonesMap:
      title: Stream limit_conns
      description: 'Status data for all stream

        <a href="https://nginx.org/en/docs/stream/ngx_stream_limit_conn_module.html#limit_conn_zone">limit_conn zones</a>.

        '
      type: object
      additionalProperties:
        $ref: '#/components/schemas/NginxStreamLimitConnZone'
