openapi: 3.2.0
info:
  version: '9.0'
  title: NGINX Plus REST License API
  description: NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
servers:
- url: /api/9
tags:
- name: License
paths:
  /license:
    get:
      tags:
      - License
      summary: NGINX Return License Info
      operationId: getLicense
      responses:
        '200':
          description: Success
          x-microcks-refs:
          - name: getLicense200Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxLicenseObject'
              example:
                eval: false
                active_till: 1749268757
                reporting:
                  healthy: true
                  fails: 2
                  grace: 15551961
                  uuid: 13754cba-29fb-53e5-c32e-a6cf57c84b01
        '404':
          description: Unknown version (*UnknownVersion*)
          x-microcks-refs:
          - name: getLicense404Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    NginxLicenseObject:
      title: License
      description: 'License and usage reporting status of NGINX Plus instance.

        '
      properties:
        eval:
          type: boolean
          description: Indicates whether NGINX Plus license is trial.
          readOnly: true
          example: false
        active_till:
          type: integer
          description: The Unix timestamp of license expiration.
          readOnly: true
          example: 0
        reporting:
          type: object
          properties:
            healthy:
              type: boolean
              description: Indicates whether the reporting state is still considered healthy despite recent failed attempts.
              readOnly: true
              example: false
            fails:
              type: integer
              description: The number of failed reporting attempts, reset each time the usage report is successfully sent.
              readOnly: true
              example: 0
            grace:
              type: integer
              description: The number of seconds before traffic processing is stopped after unsuccessful report attempt.
              readOnly: true
              example: 0
            uuid:
              type: string
              description: The ID of NGINX Plus instance in the UUID format.
              readOnly: true
              example: example-uuid
          example: {}
      example:
        eval: false
        active_till: 1749268757
        reporting:
          healthy: true
          fails: 2
          grace: 15551961
          uuid: 13754cba-29fb-53e5-c32e-a6cf57c84b01
    NginxError:
      title: Error
      description: 'nginx error object.

        '
      type: object
      properties:
        error:
          type: object
          properties:
            status:
              type: integer
              description: HTTP error code.
              example: 200
            text:
              type: string
              description: Error description.
              example: example-text
            code:
              type: string
              description: Internal nginx error code.
              example: 200
          example: {}
        request_id:
          type: string
          description: The ID of the request, equals the value of the <a href="https://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_id">$request_id</a> variable.
          example: example-request_id
        href:
          type: string
          description: Link to reference documentation.
          example: example-href
